[package]
name = "krakensync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.1"
anyhow = "1.0.66"
cid = "0.8.6"
multihash = "0.16.3"
parking_lot = "0.12.1"
